server:
  port: 8080
spring:
  profiles:
    active: dev
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/morrle?useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
  messages:
      cache-seconds: 1
#logging:
#  level:
#    org.springframework.web: debug
cache:
  timeToLiveSeconds: 3600
  ehcache:
    maxBytesLocalHeap: 16M
