security.basic.enabled: false
spring:
  profiles:
    active: dev
async:
  corePoolSize: 2
  maxPoolSize: 50
  queueCapacity: 10000

mail:
  host: localhost
  port: 25
  username:
  password:
  protocol: smtp
  tls: false
  auth: false
  from: bookstore@localhost
swagger:
  title: bookstore API
  description: bookstore applications and beyond!
  termsOfServiceUrl: http://morrle.ngfile.com/
  contact:
  license: Apache 2.0
  licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
